### PR TITLE
Fix ghcjs/ghcjs#472 update shims for JVM

### PR DESCRIPTION
**Pull request by mmhelloworld**
# Shims for the JVM

This pull request has 3 main changes:

## Platform detection

Java's Nashorn provides the global `Java` variable which can be used to detect if we are running under JVM. The `Java` variable is used to import Java classes like:

```
var ArrayList = Java.type('java.util.ArrayList');
var arrayListInstance = new ArrayList();
```
 
## Command line arguments

Nashorn provides a global `arguments` variable to access command line arguments passed to `jjs`(the JVM JavaScript launcher).

The arguments can be passed like:
```
jjs Main.jsexe/all.js -- foo 1 bar 4
```

## Exiting the JVM
JVM can be exited with `java.lang.System.exit(code)` from JavaScript code.

### CODE REVIEW

**Comment by luite** [comment]
Thanks, the change looks good. Although the `gitignore` file looks like a more or less random collection of lines. Can you remove it from this PR? I'd be happy to accept a new one with ignore patterns that are more likely to be relevant to this repo.

**Comment by mmhelloworld** [comment]
Sure, I can take that out. I took the gitignore file from [here](
https://github.com/github/gitignore/blob/master/Haskell.gitignore) and
added `*.iml` file to ignore IntelliJ files. I am not really sure what is
relevant to this repo. Do you have a list or is there some other repo that
has more relevant list that we can use it here?

**Comment by mmhelloworld** [comment]
I have removed `.gitignore` and updated the pull request.

**Comment by luite** [comment]
Thanks, I squashed your commits and added it to master (separate merge commit only makes things messier here i think)

**Comment by mmhelloworld** [comment]
Ah, sorry, I should have squashed it. Thank you for merging!

**Pull request closed without merging**
